// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gorcz/ports/internal/datastore (interfaces: Datastore)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	port "github.com/gorcz/ports/pkg/model/port"
)

// MockDatastore is a mock of Datastore interface.
type MockDatastore struct {
	ctrl     *gomock.Controller
	recorder *MockDatastoreMockRecorder
}

// MockDatastoreMockRecorder is the mock recorder for MockDatastore.
type MockDatastoreMockRecorder struct {
	mock *MockDatastore
}

// NewMockDatastore creates a new mock instance.
func NewMockDatastore(ctrl *gomock.Controller) *MockDatastore {
	mock := &MockDatastore{ctrl: ctrl}
	mock.recorder = &MockDatastoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatastore) EXPECT() *MockDatastoreMockRecorder {
	return m.recorder
}

// UpsertPort mocks base method.
func (m *MockDatastore) UpsertPort(arg0 context.Context, arg1 *port.Port) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPort", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertPort indicates an expected call of UpsertPort.
func (mr *MockDatastoreMockRecorder) UpsertPort(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPort", reflect.TypeOf((*MockDatastore)(nil).UpsertPort), arg0, arg1)
}
